#
# MCBootstrap main configuration file

Settings:
  bootAllObjectsOnStart: false
  enableDebug: false # More information about runtime and objects
  screenNamePattern: 'MCB-%name%' # Allowed variables: %name% and %priority%
  eachServerStartDelay: 3 # Delay in seconds between objects starts (use 0 to disable(
  reverseStartOrderOnStop: false # Inverse priority of all objects

# Objects example configuration
Booting Objects:
  server1:
    type: SERVER
    priority: NORMAL # Control startup order of all objects, NORMAL by default
    bootCommand: 'java -jar Server.jar' # Shell command executed in new screen
    stopCommand: 'stop' # Server termination command, empty by default
    directory: '/example/servers/server1/'
  server2:
    type: SERVER
    priority: HIGH
    port: 25565 # if not specified, it will be read from the server.properties or from another configuration files
    autoRestart: true # Start this object again after screen shutdown, disabled by default
    bootCommand: 'java -jar Server.jar'
    stopCommand: 'stop'
    directory: '/example/servers/server2/'
  serversGroup1:
    type: GROUP
    priority: NORMAL
    commonHost: localhost # All servers in group will have this host
    bootCommand: 'java -jar Server.jar'
    stopCommand: 'stop'
    directory: '/example/servers/serversGroup1/'
  serversGroup2:
    type: GROUP
    priority: HIGHEST
    firstPort: 25600 # First server starts on this port, second this + 1, third this + 2, etc
    autoRestart: true
    bootCommand: 'java -jar Server.jar'
    stopCommand: 'stop'
    directory: '/example/servers/serversGroup2/'
  primaryServer:
    type: PRIMARY_SERVER
    priority: LOW
    uniqueFilesPolicy: RANDOM # Can be 'INORDER', 'RANDOM' or 'CUSTOM' (extension). More information on wiki
    bootCommand: 'java -jar MinigameServer.jar'
    stopCommand: 'stop'
    clonesCount: 5 # Number of cloned servers to generate
    firstPort: 30000
    autoRestart: false
    directory: '/example/servers/myminigame/primaryServerDirecory/' # Original server dirictory
    generationDirectory: '/example/servers/myminigame/arenas/' # Cloned servers folders will be generated here
  application1:
    type: APPLICATION # Means you can start anything you want (scripts, standalone aps, services and etc)
    priority: HIGHEST
    bootCommand: 'java -jar SomeStandaloneScriptOrApplication.jar'
    stopCommand: 'break' # Don't use stopCommand if your app or script doesn't support that
    directory: '/example/applications/app1/'