#
# MCBootstrap main configuration file

Settings:
  bootAllOnStart: false
  enableDebug: true
  screenNamePattern: 'MCB-%name%'
  eachServerStartDelay: 5
  reverseStartOrderOnStop: false

Booting Objects:
  server1:
    type: SERVER
    priority: NORMAL
    javaCommand: 'java -jar Server.jar'
    directory: '/example/servers/serverDirecory1/'
  server2:
    type: SERVER
    priority: HIGH
    javaCommand: 'java -jar Server.jar'
    directory: '/example/servers/serverDirecory2/'
  serversGroup:
    type: GROUP
    priority: NORMAl
    javaCommand: 'java -jar Server.jar'
    directory: '/example/servers/serversDirectory/'
  primaryServer:
    type: PRIMARY_SERVER
    priority: LOW
    uniqueFilesPolicy: RANDOM
    javaCommand: 'java -jar MinigameServer.jar'
    copiesCount: 5
    firstPort: 30000
    directory: '/example/servers/primaryServerDirecory/'
    generationDirectory: '/example/servers/arenas/'
